# Generated by Django 5.2 on 2025-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_name', models.CharField(max_length=100)),
                ('seeker_email', models.EmailField(max_length=254)),
                ('complaint_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
