# Generated by Django 5.2 on 2025-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
