# Generated by Django 5.2 on 2025-05-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0002_remove_property_id_property_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Inlisted', 'Inlisted'), ('Rejected', 'Rejected'), ('Sold', 'Sold')], default='Pending', max_length=20),
        ),
    ]
