# Generated by Django 5.2 on 2025-05-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0004_alter_property_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='additional_images',
        ),
    ]
