# Generated by Django 5.2 on 2025-05-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gov_id_proof', models.ImageField(upload_to='gov_id_proofs/')),
                ('land_certificate', models.ImageField(upload_to='land_certificates/')),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('registration_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('id_proof', models.ImageField(upload_to='id_proofs/')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('registration_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('booking_status', models.CharField(choices=[('No Booking', 'No Booking'), ('Pending', 'Pending'), ('Booked', 'Booked'), ('Already Booked', 'Already Booked')], default='No Booking', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
