# Generated by Django 5.2 on 2025-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_owner_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
